### PR TITLE
Render dots and action button at bottom of slide container

### PR DESCRIPTION
**Pull request by chrissnyder**
Pushes the dots and action button to the bottom of the slide container. Makes it such that inconsistent length of text in each slide doesn't cause them to move up and down.

### CODE REVIEW

**Comment by aweiksnar** [comment]
Is there other css that you're using with this? I checked it out using /example/custom.html and /example/default.html and am getting overlap with the text

Do you think it'd be cool to do something like grab the largest `getBoundingClientRect().height` of each `.slide-tutorial-slide` and set the min-height to the largest one via js?

It could be a constructor param like constantHeight: true

**Comment by chrissnyder** [comment]
Ah crap, I was testing it in the context of plankton. I'm dumb, my apologies.

Yea, having it configurable would be cool. Updates shortly.

**Comment by chrissnyder** [comment]
Seems like it took more code than it should have, but how's that look? Configurable via `constantHeight`. It does change the way the slide tutorial is hidden from `display: none` to `height: 0; overflow: hidden` so I could calculate slide heights.

**Comment by aweiksnar** [comment]
Looks solid!  This PR made me notice a bug with how default boolean values are set--I'll merge this in and then fix that separately as a v0.0.5

**Comment by aweiksnar** [comment]
:shipit: :shipit:
Updated on npm

**Pull request merged**
